services:

  redis:
    image: redis:alpine
    container_name: redis

  coordinator:
    build: ./coordinator
    container_name: coordinator
    volumes:
      - ./worker_nodes:/app/worker_nodes
    ports:
      - "8000:8000"
    environment:
      - REDIS_HOST=redis
    depends_on:
      - redis

  worker_1:
    build: ./worker_nodes
    command: celery -A app.celery_worker worker --loglevel=info
    environment:
      - WORKER_ID=worker_1
    depends_on:
      - redis

  worker_2:
    build: ./worker_nodes
    command: celery -A app.celery_worker worker --loglevel=info
    environment:
      - WORKER_ID=worker_2
    depends_on:
      - redis

  worker_3:
    build: ./worker_nodes
    command: celery -A app.celery_worker worker --loglevel=info
    environment:
      - WORKER_ID=worker_2
    depends_on:
      - redis

