services:

  redis:
    image: redis:alpine
    container_name: redis

  coordinator:
    build: ./coordinator
    command: uvicorn app.api:app --host 0.0.0.0 --port 8000
    container_name: coordinator
    volumes:
      - ./worker_nodes:/app/worker_nodes
    ports:
      - "8000:8000"
    environment:
      - REDIS_HOST=redis
    depends_on:
      - redis

  worker_1:
    build: ./worker_nodes
    command: ./start_and_register.sh
    environment:
      - WORKER_ID=worker_1
    depends_on:
      - coordinator

  worker_2:
    build: ./worker_nodes
    command: ./start_and_register.sh
    environment:
      - WORKER_ID=worker_2
    depends_on:
      - coordinator

  worker_3:
    build: ./worker_nodes
    command: ./start_and_register.sh
    environment:
      - WORKER_ID=worker_3
    depends_on:
      - coordinator
